# Generated by Django 5.1.2 on 2025-02-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSP_02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicroom',
            old_name='mass_pause',
            new_name='guest_pause',
        ),
    ]
