# Generated by Django 5.1.2 on 2025-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSP_02', '0002_rename_mass_pause_musicroom_guest_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicroom',
            name='room_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
