# Generated by Django 5.1.2 on 2025-03-02 15:18

import FSP_02.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSP_02', '0003_alter_musicroom_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicroom',
            name='room_id',
            field=models.CharField(default=FSP_02.models.get_unique_id, max_length=10, unique=True),
        ),
    ]
