# Generated by Django 5.1.2 on 2025-03-02 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSP_02', '0004_alter_musicroom_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicroom',
            name='member_limit',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Member limit must be at least 1'), django.core.validators.MaxValueValidator(10, message='Member limit cannot exceed 10')]),
        ),
    ]
