# Generated by Django 5.1.2 on 2024-11-22 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ml_types', models.CharField(choices=[('mt1', 'm_type1'), ('mt2', 'm_type2'), ('mt3', 'm_type3'), ('mt4', 'm_type4'), ('mt5', 'm_type5')], max_length=3)),
            ],
        ),
    ]
