# Generated by Django 5.1.2 on 2024-11-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjApp_01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='model1',
            name='images',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='model1',
            name='ml_types',
            field=models.CharField(choices=[('Model_1', 'mtype1'), ('Model_2', 'mtype2'), ('Model_3', 'mtype3'), ('Model_4', 'mtype4'), ('Model_5', 'mtype5')], max_length=10),
        ),
    ]
