# Generated by Django 5.1.2 on 2024-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjApp_01', '0002_model1_description_alter_model1_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=6),
        ),
    ]
