# Generated by Django 5.1.2 on 2024-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjApp_01', '0003_model1_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model1',
            name='ml_types',
            field=models.CharField(choices=[('Model_1', 'MT-1'), ('Model_2', 'MT-2'), ('Model_3', 'MT-3'), ('Model_4', 'MT-4'), ('Model_5', 'MT-5')], max_length=10),
        ),
    ]
