# Generated by Django 5.1.2 on 2024-11-27 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjApp_01', '0004_alter_model1_ml_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='modelCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(max_length=50)),
                ('cert_issued_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cert_valid_adte', models.DateTimeField()),
                ('cert_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cert', to='DjApp_01.model1')),
            ],
        ),
        migrations.CreateModel(
            name='modelReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('md', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='DjApp_01.model1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='modelStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=100)),
                ('st_address', models.CharField(max_length=100)),
                ('st_varities', models.ManyToManyField(related_name='model_store', to='DjApp_01.model1')),
            ],
        ),
    ]
