# Generated by Django 5.1.2 on 2024-12-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSP_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user',
        ),
    ]
