# Generated by Django 5.1.2 on 2024-12-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSP_01', '0002_rename_author_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='author',
        ),
    ]
